name: Build and Deploy to ACK

on:
  push:
    branches:
      - master

env:
  REGION_ID: cn-chengdu
  REGISTRY: registry.cn-chengdu.aliyuncs.com
  NAMESPACE: wizz-project
  IMAGE: jiuxing
  TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to ACR with the AccessKey pair
        uses: aliyun/acr-login@v1
        with:
          login-server: https://registry.cn-chengdu.aliyuncs.com
          username: "${{ secrets.REGISTRY_USERNAME }}"
          password: "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Build and push image to ACR
        run: |
          docker build --tag "$REGISTRY/$NAMESPACE/$IMAGE:$TAG" .  
          docker push "$REGISTRY/$NAMESPACE/$IMAGE:$TAG"
          docker tag "$REGISTRY/$NAMESPACE/$IMAGE:$TAG" "$REGISTRY/$NAMESPACE/$IMAGE:latest"
          docker push "$REGISTRY/$NAMESPACE/$IMAGE:latest"